map_type: costmap

obstacle_range: 0.2
raytrace_range: 1.6

transform_tolerance: 0.3

robot_radius: 0.2
inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}

pdist_scale: 2.2
gdist_scale: 0.8
occdist_scale: 0.1

meter_scoring: true

xy_goal_tolerance: 0.05
yaw_goal_tolerance: 0.02
