map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

transform_tolerance: 0.3

robot_radius: 0.2
inflation_radius: 0.3

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}

pdist_scale: 2.5
gdist_scale: 4.1
occdist_scale: 1.5

meter_scoring: true

sim_time: 1.5
#controller_frequency: 18

xy_goal_tolerance: 0.05
yaw_goal_tolerance: 0.05
