global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 40.0
   publish_frequency: 20.0
   width: 80.0
   height: 80.0
   resolution: 0.1
   static_map: true
   rolling_window: false
