local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 25.0
   publish_frequency: 15.0
   width: 30.0
   height: 30.0
   resolution: 0.1
   static_map: false
   rolling_window: true
